version: '2'
services:
  database:
    image: unters1/sales_database
    privileged: true
    hostname: quickstart.cloudera
    command: /usr/bin/docker-quickstart
    ports:
      - "8020:8020"   # HDFS 
      - "8022:22"     # SSH
      - "7180:7180"   # Cloudera Manager
      - "8888:8888"   # Hue
      - "11000:11000" # Oozie
      - "5000:5000" # HDFS Rest Namenode
      - "5001:5001" # HDFS Rest Datanode
      - "2181:2181"   # Zookeeper
      - "8088:8088"   # YARN Resource Manager
      - "19888:19888" # MapReduce Job History
      - "50030:50030" # MapReduce Job Tracker
      - "8983:8983"   # Solr
      - "16000:16000" # Sqoop Metastore
      - "8042:8042"   # YARN Node Manager
      - "60010:60010" # HBase Master
      - "60030:60030" # HBase Region
      - "9090:9090"   # HBase Thrift
      - "8080:8080"   # HBase Rest
      - "7077:7077"   # Spark Master
      - "21000:21000"   # Impala Deamon ODBC
      - "21050:21050"   # Impala Deamon JDBC
    tty: true
    stdin_open: true
    volumes: 
      - /var/shared_cloudera_quickstart:/media/shared_from_local