version: '2'
services:
  database:
    image: unters1/sales_database:latest
    privileged: true
    hostname: quickstart.cloudera
    command: /usr/bin/docker-quickstart
    ports:
      - "21000:21000"   # Impala Deamon ODBC
      - "21050:21050"   # Impala Deamon JDBC
    tty: true
    stdin_open: true
    volumes: 
      - /var/shared_cloudera_quickstart:/media/shared_from_local